### ISSUE TITLE
机器人昵称为空时报错

### ISSUE THREAD

**Issue by wdnmda0j** [RSRH-Rs/whoatme#4]
经过排查报错原因为机器人未填写昵称
报错信息如下：
[2024-11-02 14:52:59,548 nonebot] ERROR: Failed to import "hoshino.modules.whoatme.utils", error: string index out of range
[2024-11-02 14:52:59,549 nonebot] ERROR: string index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/HoshinoBot/hoshino/modules/whoatme/__init__.py", line 6, in <module>
    from .utils import *
  File "/HoshinoBot/hoshino/modules/whoatme/utils.py", line 9, in <module>
    from .config import expire_time
  File "/HoshinoBot/hoshino/modules/whoatme/config.py", line 11, in <module>
    {NICKNAME[0]}最多为每个用户单个群聊保存100条消息哦！
IndexError: string index out of range
[2024-11-02 14:52:59,557 nonebot] ERROR: Failed to import "hoshino.modules.whoatme.config", error: string index out of range
[2024-11-02 14:52:59,558 nonebot] ERROR: string index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/HoshinoBot/hoshino/modules/whoatme/__init__.py", line 6, in <module>
    from .utils import *
  File "/HoshinoBot/hoshino/modules/whoatme/utils.py", line 9, in <module>
    from .config import expire_time
  File "/HoshinoBot/hoshino/modules/whoatme/config.py", line 11, in <module>
    {NICKNAME[0]}最多为每个用户单个群聊保存100条消息哦！
IndexError: string index out of range

**Comment by RSRH-Rs** [comment]
去设置一下名字就行 如果不想设置名字的话去这个插件的config里面把这句话改成 ”” 空字符串就好了
